name: assignment3
description: HCI Assignment 3
publish_to: none
version: 1.0.0+1

environment:
  sdk: ">=2.19.1 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  flex_color_scheme: ^6.1.2
  flutter_hooks: ^0.18.5+1
  functional_widget_annotation: ^0.10.0

dev_dependencies:
  build_runner: ^2.3.3
  flutter_lints: ^2.0.0
  functional_widget: ^0.10.1

flutter:
  uses-material-design: true
